### ISSUE TITLE
Unable to get any product details except home page [BUG]

### ISSUE THREAD

**Issue by sshajiya** [evershopcommerce/evershop#190]
**Describe the bug**
Successfully able to install the application in ubuntu with 16.x node version

root@ip-x.x.x.x:~/my-app# npm run start

> my-app@0.1.0 start
> evershop start

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/node-config/node-config/wiki/Strict-Mode

   ┌─────────────────────── EverShop ───────────────────────┐
   │                                                        │
   │   Your website is running at "http://localhost:1000"   │
   │                                                        │
   └────────────────────────────────────────────────────────┘

**To Reproduce**
1. Go to 'homepage'
2. Click on 'any of the collection site'

**Expected behavior**
should able to redirect to the collection page

**Actual**
404 Page Not Found
The page you requested does not exist.
[Continue shopping](http://x.x.x.x:1000/)

**Screenshots**

**Background (please complete the following information):**
 - NodeJS Version 16.x 
 - MySQL Version default
 - EverShop Version 0.1.0
 - OS: [e.g. Window, Ubuntu, Mac-OS] Ubuntu
 - Browser [e.g. Chrome, Safari] chrome

**Additional context**
tokenPayLoad { user: null, sid: '8fe0ed75-d5c4-49b1-a492-6f87454ff761' }
tokenPayLoad { user: null, sid: '3f0c61f9-0a8c-4cbf-ae27-00fff8b80073' }
tokenPayLoad {
  user: null,
  sid: '3f0c61f9-0a8c-4cbf-ae27-00fff8b80073',
  iat: 1675079412,
  exp: 1675252212
}
tokenPayLoad {
  user: null,
  sid: '3f0c61f9-0a8c-4cbf-ae27-00fff8b80073',
  iat: 1675079412,
  exp: 1675252212
}

**Comment by treoden** [comment]
Dear @sshajiya ,

I guess you are referring to 3 buttons "Shop kids", "Shop men" and "Shop women".
Those buttons are linked to corresponding category (kids, men, women). However, those category does not exit after fresh installation. You have to create them yourself. (Fresh installation does not contains any data)

In features (near feature). We will make that block as a widget that can be edited from admin instead of hardcode. So admin user can edit and link to somewhere else or even remove it

Thank you
