### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by javijuji** [evershopcommerce/evershop#312]
Will we eventually get a docker image? Would really simplify installation process.

**Comment by Technetium1** [comment]
Getting _at least_ a Dockerfile should be high priority.

**Comment by kaysond** [comment]
The way evershop is architected doesn't lend itself well to docker. It doesn't really work out of the box. You need to write your own theme because what ships by default has hardcoded images and featured categories. Then you have to actually build the app (which you could do in the dockerfile) and any themes, so you can't really store the app in the image.

What I did is run a plain old node docker container, and bind mount a directory with the source code and my theme from the host. Then I just attach and do an `npm build && npm run`.

The build process also doesn't seem to run incrementally, meaning if you run it twice in a row, the second rebuilds the whole app even though nothing has changed.

For this to really be "dockerizeable", the app would have to come with an out-of-the-box functional default theme. If you want a custom theme, you'd probably have extend the image with your own and just rebuild the whole thing.

Ideally, there would be a way to compile the theme and just include that somewhere that evershop can load.

@treoden - I'd be happy to help contribute docker-related stuff. Feel free to hit me up on discord (@thearamadon)

**Comment by evershopcommerce** [comment]
Docker is available. Please check this document for more details 
https://evershop.io/docs/development/getting-started/installation-guide#install-evershop-using-docker
