### ISSUE TITLE
Build gets stuck at TerserPlugin - Killed

### ISSUE THREAD

**Issue by ultimate-tester** [evershopcommerce/evershop#340]
**Describe the bug**
When building and reaching the TerserPlugin stage, the build gets stuck and eventually results in "Killed". This behavior was described in this issue: https://github.com/evershopcommerce/evershop/issues/295#issuecomment-1653844938 too.

**To Reproduce**
1. user `npx create-evershop-app my-app` to initiate a new app
2. Run `npm run build`
3. Let it run, eventually it will reach the TerserPlugin

**Expected behavior**
Build to finish without errors

**Background (please complete the following information):**
 - NodeJS Version v16.18.1
 - Postgres Version 15.4
 - EverShop Version 1.0.0-rc.7
 - OS: CentOS 7

**Additional context**
Increasing the max ram allocation to NodeJS using `NODE_OPTIONS=--max_old_space_size=8192` does not make any difference.

**Comment by ultimate-tester** [comment]
I moved the whole project over to my other server with 16gb of ram, built it there. The memory footprint was more than 6 gigabyte. Isn't that a bit ridiculous? Is there anything that you can do from your perspective to tame the terser module a bit, or is this really on the terser side?

**Comment by treoden** [comment]
Hi @ultimate-tester ,

Yes this issue was reported in others project too. For example : https://github.com/webpack-contrib/terser-webpack-plugin/issues/217

Look like Terser plugin is not a fast action. Lets see if we can make an improvement to this build process.
For now, we will add a flag to the build command to skip the minify. It will be available in the next release

Thanks

**Comment by treoden** [comment]
Hi,

For anyone who run into this issue. Please try the below command to skip the minify:

`npm run build -- --skip-minify`

Thanks
