### ISSUE TITLE
[FEATURE REQUEST] Ability to drop an order from the admin side

### ISSUE THREAD

**Issue by trilloc** [evershopcommerce/evershop#392]
**Is your feature request related to a problem? Please describe.**
Some of the orders fail during the payment process and may need to be dropped 

**Describe the solution you'd like**
Admin should have ability to click on order (and if it is not paid yet) drop/delete the order

**Comment by evershopcommerce** [comment]
Hi @trilloc,

We suggest not to allow deleting order from admin. For your case, the solution could be buiding a scheduled job to scan for the pending/failed payment order after specified amount of time, then cancel it

thanks

**Comment by trilloc** [comment]
Thanks for your reply. How do we cancel the order in the admin panel now?

Cheers

**Comment by evershopcommerce** [comment]
Hi @trilloc ,
Since the cancellation logic can be vary depends on the business, we do not have the cancel button by default. You can always add an extension to take care of the cancellation process fit with your business. You can also add a cancel button to the order detail page easily. My point is the cancellation is not just a “Cancel” button, it is all about your business requirements 

thanks

**Comment by trilloc** [comment]
Ok, I see. thank you for the clarification 👍
