### ISSUE TITLE
[BUG] ailed prop type: Invalid prop `variant` of value `secondary` supplied to `Badge`, expected one of ["default","success","info","attention","critical","warning","new"]

### ISSUE THREAD

**Issue by treoden** [evershopcommerce/evershop#93]
**Describe the bug**
A warning message when visiting the order listing page from admin panel

**To Reproduce**
1. Start the project in development mode
2. Go to admin panel and visit the order listing page (Must have some order)
3. See error in the developer console

**Expected behavior**
The error message should disappear

**Screenshots**
![Screenshot from 2022-08-21 21-31-15](https://user-images.githubusercontent.com/6950941/185796187-6443031f-b61d-4632-b271-efc9e53f1d4d.png)

**Comment by timagixe** [comment]
Hello @treoden, please assign this issue on me, I will create a PR for this issue in the next 1-2 days. Cheers!

**Comment by timagixe** [comment]
@treoden what should be the default badge variant for `pending` payment status? Should it be `default` or which one of these - `['default', 'success', 'info', 'attention', 'critical', 'warning', 'new']`?

**Comment by timagixe** [comment]
@treoden by the default it is set to be `secondary`. Such a badge variant doesn't exist.

From what I see, badge variant of type `secondary` seems to be the result of misconfiguration/typo:

https://github.com/evershopcommerce/evershop/blob/main/packages/core/bin/install/templates/config.json#L62-L67

That's why I am clarifying what should be the variant of badge of pending status.

**Comment by timagixe** [comment]
@treoden I have opened PR #95, which sets `default` badge for pending payment status.

Please let me know if it requires to be different.
